export const businessIndustries = [
  "Agriculture",
  "Automotive",
  "Apparel & Fashion",
  "Aviation",
  "Banking",
  "Biotechnology",
  "Chemicals",
  "Construction",
  "Consulting",
  "Education",
  "Electronics",
  "Energy",
  "Engineering",
  "Entertainment",
  "Environmental",
  "Executive Management",
  "Finance & Insurance (Banking, Investments, Wealth Management)",
  "Fishery",
  "Food & Beverage",
  "Forestry",
  "Government/Public Administration",
  "Healthcare (Medical services, Pharmaceuticals)",
  "Hospitality (Hotels, Restaurants, Food Services)",
  "Human Resources",
  "Information Technology (IT)",
  "Insurance",
  "Legal",
  "Logistics & Supply Chain",
  "Manufacturing (general)",
  "Marketing & Advertising",
  "Media & Entertainment",
  "Mining",
  "Non-Profit/NGOs",
  "Oil and Gas",
  "Pharmaceuticals",
  "Public Relations",
  "Real Estate",
  "Research & Development (R&D)",
  "Retail Trade",
  "Telecommunications",
  "Transportation",
  "Utilities (Power, Gas, Water)",
  "Wholesale Trade",
];
