export const businessIndustries = [
  "Agriculture",
  "Mining",
  "Oil and Gas",
  "Forestry",
  "Fishing",
  "Manufacturing (general)",
  "Automotive",
  "Chemicals",
  "Construction",
  "Utilities (Power, Gas, Water)",
  "Electronics",
  "Retail Trade",
  "Wholesale Trade",
  "Hospitality (Hotels, Restaurants, Food Services)",
  "Transportation",
  "Finance & Insurance (Banking, Investments, Wealth Management)",
  "Real Estate",
  "Healthcare (Medical services, Pharmaceuticals)",
  "Media & Entertainment",
  "Information Technology (IT)",
  "Telecommunications",
  "Research & Development (R&D)",
  "Education",
  "Consulting",
  "Government/Public Administration",
  "Non-Profit/NGOs",
  "Executive Management",
];
