export const predefinedTasks = [
  "Poster",
  "Video",
  "Story",
  "Motion Graphics",
  "Animation",
  "Grid",
  "Posting",
  "Account Creation",
  "Flyer",
  "Profile",
  "Menu",
  "FB Cover",
  "Whatsapp Cover",
  "Profile Picture",
  "Highlite Cover",
  "Ad Post",
  "Shooting",
  "Meeting",
  "Connect",
  "Followup",
];
