export const predefinedTasks = [
  "Account Creation",
  "Ad Post",
  "Animation",
  "Branding",
  "Brochure",
  "Connect",
  "Content Creation",
  "Copywriting",
  "Email Marketing",
  "FB Cover",
  "Flyer",
  "Followup",
  "Grid",
  "Highlite Cover",
  "Logo Design",
  "Meeting",
  "Menu",
  "Motion Graphics",
  "Photography",
  "Poster",
  "Posting",
  "Profile",
  "Profile Picture",
  "Reels",
  "SEO",
  "Shooting",
  "Social Media Management",
  "Story",
  "Video",
  "Videography",
  "Website Design",
  "Website Development",
  "Whatsapp Cover",
];
