
-- Enable pg_cron
create extension if not exists pg_cron with schema extensions;
grant usage on schema cron to postgres;
grant all on all tables in schema cron to postgres;

-- Create app_settings table
create table if not exists public.app_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb
);
alter table public.app_settings enable row level security;
create policy "Allow public read-only access" on public.app_settings for select using (true);
create policy "Allow admin write access" on public.app_settings for insert with check (auth.role() = 'service_role');
create policy "Allow admin update access" on public.app_settings for update with check (auth.role() = 'service_role');


-- Add attachments column to tasks
alter table if exists public.tasks
add column if not exists attachments jsonb;

-- Function to delete attachments from storage
create or replace function public.delete_task_attachments(task_id uuid)
returns void
language plpgsql
security definer
as $$
declare
  attachment_path text;
begin
  -- Get the attachments from the task
  select attachments::jsonb ->> 'path' into attachment_path from public.tasks where id = task_id;
  
  -- If there's a file, delete it from storage
  if attachment_path is not null then
    perform storage.delete_object('attachments', attachment_path);

    -- Clear the attachment column in the task
    update public.tasks
    set attachments = null
    where id = task_id;
  end if;
end;
$$;

-- Trigger function to handle task status changes
create or replace function public.handle_task_done()
returns trigger
language plpgsql
as $$
declare
  delay_seconds int;
  job_name text;
  schedule_command text;
begin
  job_name := 'delete-attachments-' || new.id::text;

  -- Get delay from settings, default to 300 seconds (5 minutes)
  select (value->>0)::int into delay_seconds from public.app_settings where key = 'attachment_deletion_delay';
  if not found then
    delay_seconds := 300;
  end if;

  -- If task is marked as "done" and has attachments
  if new.status = 'done' and old.status <> 'done' and new.attachments is not null then
    -- Schedule a job to delete attachments
    schedule_command := format('select public.delete_task_attachments(%L)', new.id::text);
    perform cron.schedule(
      job_name,
      (interval '1 second' * delay_seconds)::text,
      schedule_command
    );
  
  -- If task is moved from "done" to another status
  elsif new.status <> 'done' and old.status = 'done' then
    -- Cancel the scheduled job
    perform cron.unschedule(job_name);
  end if;

  return new;
end;
$$;

-- Drop existing trigger to avoid errors on re-run
drop trigger if exists on_task_status_change on public.tasks;

-- Create the trigger on the tasks table
create trigger on_task_status_change
  after update on public.tasks
  for each row
  execute function public.handle_task_done();

-- Insert default deletion delay if not present
insert into public.app_settings (key, value)
values ('attachment_deletion_delay', '300')
on conflict (key) do nothing;
