
create table "public"."official_holidays" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "date" date not null,
    "description" text,
    "user_id" uuid
);


alter table "public"."official_holidays" enable row level security;

CREATE UNIQUE INDEX official_holidays_pkey ON public.official_holidays USING btree (id);

alter table "public"."official_holidays" add constraint "official_holidays_pkey" PRIMARY KEY using index "official_holidays_pkey";

alter table "public"."official_holidays" add constraint "official_holidays_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."official_holidays" validate constraint "official_holidays_user_id_fkey";

create policy "Allow authenticated users to read all holidays"
on "public"."official_holidays"
as permissive
for select
to authenticated
using (true);

create policy "Allow authenticated users to add holidays"
on "public"."official_holidays"
as permissive
for insert
to authenticated
with check (true);
