
CREATE TABLE official_holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    date DATE NOT NULL,
    description TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

ALTER TABLE public.official_holidays ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read holidays"
ON public.official_holidays
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow users to insert their own holidays"
ON public.official_holidays
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow company admins to insert official holidays"
ON public.official_holidays
FOR INSERT
TO authenticated
WITH CHECK (user_id IS NULL AND (SELECT role_id FROM public.profiles WHERE id = auth.uid()) IN (SELECT id FROM public.roles WHERE name = 'Falaq Admin'));

CREATE POLICY "Allow users to update their own holidays"
ON public.official_holidays
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to delete their own holidays"
ON public.official_holidays
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Allow company admins to manage official holidays"
ON public.official_holidays
FOR ALL
TO authenticated
USING (user_id IS NULL AND (SELECT role_id FROM public.profiles WHERE id = auth.uid()) IN (SELECT id FROM public.roles WHERE name = 'Falaq Admin'))
WITH CHECK (user_id IS NULL AND (SELECT role_id FROM public.profiles WHERE id = auth.uid()) IN (SELECT id FROM public.roles WHERE name = 'Falaq Admin'));
