
create table if not exists public.industries (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    constraint industries_pkey primary key (id)
);

create table if not exists public.work_types (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    constraint work_types_pkey primary key (id)
);
